services:
    bitbag.menu.content_management:
        class: BitBag\CmsPlugin\Menu\ContentManagementMenuBuilder
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: buildMenu }

    bitbag.event_listener.image_block_upload:
        class: BitBag\CmsPlugin\EventListener\ImageBlockUploadListener
        arguments:
            - "@sylius.image_uploader"
        tags:
            - { name: kernel.event_listener, event: bitbag.block.pre_create, method: uploadImage }
            - { name: kernel.event_listener, event: bitbag.block.pre_update, method: uploadImage }

    bitbag.event_listener.video_block_upload:
        class: BitBag\CmsPlugin\EventListener\VideoBlockUploadListener
        arguments:
            - "@bit_bag.cms_plugin.uploader.video_uploader"
        tags:
            - { name: kernel.event_listener, event: bitbag.block.pre_create, method: uploadVideo }
            - { name: kernel.event_listener, event: bitbag.block.pre_update, method: uploadVideo }